force-app/main/default/objects/FiveNineResource__mdt/FiveNineResource__mdt.object-meta.xml
<CustomObject>
    <description>Grouping Five9 Service configuration</description>
    <label>Five9 Resource</label>
    <pluralLabel>Five9 Resources</pluralLabel>
</CustomObject>

force-app/main/default/objects/FiveNineResource__mdt/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <label>Base URL</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FiveNineResource__mdt/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <description>HTTPS or WSS</description>
    <label>Protocol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HTTPS</fullName>
                <default>true</default>
                <label>HTTPS</label>
            </value>
            <value>
                <fullName>WSS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FiveNineResource__mdt/fields/ResourceURL__c.field-meta.xml
<CustomField>
    <fullName>ResourceURL__c</fullName>
    <label>Resource URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FiveNineSocketAuraService.cls
public with sharing class FiveNineSocketAuraService {
	@AuraEnabled(cacheable=true)
	public static String getFive9Config () {
		Set<Id> five9CallCenters = new Set<Id>();
		for (CallCenter cc : [SELECT Id FROM CallCenter WHERE Name LIKE 'Five9%']) {
			five9CallCenters.add(cc.Id);
		}
		User currentUser = [SELECT CallCenterId from User WHERE Id = :UserInfo.getUserId()];

		ViewModel vm = new ViewModel();
		vm.isFive9User = five9CallCenters.contains(currentUser.CallCenterId);
		vm.resources = [
			SELECT Id,
				BaseUrl__c,
				DeveloperName,
				MasterLabel,
				Protocol__c,
				ResourceURL__c
			FROM FiveNineResource__mdt];

			return JSON.serialize(vm);
	}

	public class ViewModel {
		public Boolean isFive9User {get;set;}
		public List<FiveNineResource__mdt> resources {get;set;}
	}
}